language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7"  # TravisCI blows up with some bizarre requirements issue when attempting to do test-requirements for Py 3.7
  - "3.8"
  - "nightly"

services:
  - xvfb

# command to run tests
script: pytest

install: pip install -r test-requirements.txt